Домашнее задание 1, "Бор"
Decorus2009/CSC.NET pull request #1
Opened 2017-09-19 20:40 UTC by Decorus2009

2017-10-02 16:01 UTC, VMAtm requested changes
На данный момент оценка 9/10

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Program.cs
> +
Обычно директивы импорта сортируют так, чтобы статичные импорты и создание псевдонимов (aliases) было после импорта пространств имён (сходно, например, с Python, где сначала идут общие `import`, и лишь затем конструкции `from ... import ...`.

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Program.cs
> +            }
Здесь ошибка Copy-Paste, для каждого слова проверяется, что в боре находит `Hello`.

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Program.cs
> +            var trie = new Trie();
Было бы здорово проверочный код оформить в виде Unit-тестов

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Properties/AssemblyInfo.cs
> +using System.Runtime.InteropServices;
Несмотря на то, что это системный файл, созданный не вами, было бы неплохо проверять и его на соответствие стилям - данный импорт в вашем файле не используется

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +            public void RemoveChildBy(char c)
Обычно так не делают - GC вполне справляется со сборкой мусора из содержимого generic-коллекций

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +
Здесь и далее: Обычно инициализацию `read-only` полей выносят в конструтор, например, чтобы не путать выражения вида `something = ...` и `something => ...`.

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +            internal bool IsTerminal { get; set; }
Здесь и далее: Если класс является `private`, идентификатор `internal` ничего не даёт, методы и так уже видны только родительскому классу.

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +
Возможно, более читаемый вариант был бы `Count > 0`, или вызов методе `LINQ`: `_children.Any()`

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +        {
Добавить свой тип исключения нелегко, если помнить про все стандарты (например, 3 конструтора для своего исключения, вспомогательное сообщение для пользователя): https://stackoverflow.com/q/2200241/213550 https://stackoverflow.com/q/20391287/213550

Другой вопрос, действительно ли это нужно? Код, использующий данное исключение, ориентируется на возможное брошенное исключение как на корректную работу приложения. Так использовать **исключетельные** ситуации в C# не надо - если брошено исключение, корректной работы кода по обычному сценарию не предполагается - обычно исключения логируются, и иногда пробрасываются дальше.

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +        /// Returns true if this set did not already contain the specified element
На будущее: Тройной комментарий обычно обозначает xml-документацию, чего здесь нет. Если нужен комментарий, используйте двойной: //

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +            return true;
Здесь и далее: так как текущее значение переменной никому не требуется, можно писать так: `++_size;` (этот момент упомянут в лекциях в разделе про цикл for).

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +            }
Здесь и далее: Если метод `FindLastNodeFor` будет возвращать `null` в случае неуспеха, вместо выбрасывания исключения можно будет просто использовать оператор `?.`

2017-10-02 16:01 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +                    {
Здесь и далее: В лекциях при рассказе про цикл `for` было отмечено, что, если не требуется знать текущее значение `i`, можно использовать префиксный инкремент: `++i`. Более того, весь цикл `for` можно заменить на `foreach` без потери смысла.

2017-10-03 03:54 UTC, VMAtm commented on hw1/hw1/Trie.cs
> +    {
В задании не было прямо сказано, но подразумевалось использование интерфейса для определения методов, которые нужно реализовать. Это простой способ отдать компилятору на проверку, вся ли требуемая функциональность реализована. Так же в этом случае в Unit-тестах можно определять тестируемый класс как ITrie, убирая привязку к конкретной реализации, и покрывая тестами только нужные методы.

2017-10-04 21:30 UTC, Decorus2009 commented
Здравствуйте, спасибо за подробные комментарии. Постарался учесть все сказанное.

2017-10-07 18:46 UTC, closed without merging