Домашнее задание 2, "MyNUnit"
Decorus2009/CSC.NET pull request #4
Opened 2017-10-07 19:58 UTC by Decorus2009

2017-10-23 04:06 UTC, VMAtm requested changes
На данный момент оценка 9/10 (5/6 за код, 4/4 за тесты)

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/MYNUnitTests.cs
> +namespace hw2
Имена пространств имён (как и имена проектов) принято именовать с большой буквы

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/MYNUnitTests.cs
> +        public void Before2()
Почему два метода, вроде бы одинаковых?

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public string Ignore { get; set; }
Почему не `bool`?

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public TestAttribute(Type expectedException = null, string ignore = null)
Ваши свойства и так инициализируются `null`, зачем они здесь в конструкторе?

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +            Почему-то не получилось указать через относительный путь.
Исполнение тестов может идти от папки с движком юнит теста (в папке VS), а не папки проекта.

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual("MyTestSimpleEmpty", testMethods[0].Name);
Здесь напрашивается список или массив правильных имён, куча `assert` не особо читаема

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual("MyTestIgnoredWithExpectedException", testMethods[7].Name);
Почему метод выше говорит, что методов должно быть 9, а тут сравнение только для 8?

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +                .Find(methodInfo => methodInfo.Name == "MyTestSimpleEmpty");
Вы часто приводите ваш `IEnumerable` к списку. Либо сразу его объявите списком, либо используйте методы `IEnumerable`. Можно сделать `Single` или `First`, это то же самое, что и `Find`.

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/Program.cs
> +            if (args.Length != 1)
Очень хорошо, что ваша программа проверяет переданные ей аттрибуты. Хотелось бы видеть ещё и значения по умолчанию (например, их можно сохранить в hw2 --> Properties --> Debug --> Command line arguments. Совсем хорошо было бы видеть там относительный путь.

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/Program.cs
> +                Environment.Exit(1);
Да, это вполне себе способ.

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/Properties/AssemblyInfo.cs
> +using System.Runtime.CompilerServices;
Проверяйте и автоматически создаваемые файлы - здесь `using` не нужен

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual(1, TestGroups.ToList().Count());
У списка есть свойство `Count`, можно не вызывать метод от `IEnumerable` или не приводить к списку

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestDiscoverer.cs
> +                Райдер говорит, про "possible multiple enumeration", но
Райдер, как и Решарпер, боится, что внутри класса `TestGroup` вы будете использовать перечисление. Так как вы его там используете, они правы. Более того, вы всё равно внутри класса приводите всё к `List`, так почему бы это не сделать сразу?

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestDiscoverer.cs
> +                    testGroups.Add(new TestGroup(type, beforeClassMethods, beforeMethods, testMethods, afterMethods,
Если уж переносить, то каждый параметр на своей строке, или половину на половину

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestGroup.cs
> +        public IEnumerable<MethodInfo> BeforeClassMethods { get; set; }
`set` можно убрать - вы инициализируете свойство только в конструкторе

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestResult.cs
> +        /* Я бы вместо null использовал тут Optional<>, но в C# такого нет? */
В 8 C# вроде обещают nullable для reference type, сейчас только так: `bool?` и т.д.
Поля, кстати, и так `null`, зачем в параметрах конструтора передавать эти значения

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestRunner.cs
> +                testGroup.BeforeMethods.ToList().ForEach(memberInfo => Run(type, memberInfo));
Очень плохая привычка делать `ToList` только для того, чтобы вызвать `ForEach`

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestRunner.cs
> +        private static void Run(Type type, MethodInfo methodInfo) =>
Да, это логичное предположение. Можно было ещё ругаться на то, что есть параметры у метода, отмеченного как тест

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestRunner.cs
> +    public class TestRunner
Можно сделать статичным классом

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/MYNUnitTests.cs
> +        [BeforeClass]
Все три метода `Before` почему-то не вызываются из сессии юнит тестов. Возможно, их оптимизирует компилятор, стоит проверить - у меня в покрытии тестами они отмечены как не покрытые

2017-10-23 04:06 UTC, VMAtm commented on hw2/hw2/TestResult.cs
> +        public override string ToString()
А когда вы используете этот метод?

2017-10-26 11:59 UTC, Decorus2009 commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public string Ignore { get; set; }
В условии сказано "Ignore -- для отмены запуска и указания причины". Ignore строчный, чтобы можно было указать причину 
[Test(ExpectedException = typeof(Exception), Ignore = "Ignore even this test")]
public void MyTestIgnoredWithExpectedException()
{
     Console.WriteLine("It also shouldn't be printed");
}

2017-10-26 12:13 UTC, Decorus2009 commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public TestAttribute(Type expectedException = null, string ignore = null)
Тут они, скорее всего, служат как аргументы по умолчанию. В противном случае код не компилируется, а райдер в MYNUnitTests.cs подсвечивает метод, например, 
        [Test(Ignore = "Ignore even this test")]
        public void MyTestIgnoredWithUnexpectedException()
        {
            Console.WriteLine("It also shouldn't be printed");
            throw new NullReferenceException();
        }
и говорит "Constructor 'TestAttribute' has 2 parameters but is invoked with 0 arguments'. Честно говоря, не очень понимаю, что это значит. Вроде, тут передаю же как раз два аргумента в TestAttribute

2017-10-26 12:22 UTC, Decorus2009 commented on hw2/hw2/NUnitTests.cs
> +            Почему-то не получилось указать через относительный путь.
Когда запускаю в райдере, то текущий путь, относительно которого исполняются тесты: /Applications/Rider 2017.1.1.app/Contents/lib/ReSharperHost

2017-10-26 12:25 UTC, Decorus2009 commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual(1, TestGroups.ToList().Count());
Убрал приведение к списку

2017-10-26 12:29 UTC, Decorus2009 commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual("MyTestSimpleEmpty", testMethods[0].Name);
Исправил

2017-10-26 12:31 UTC, Decorus2009 commented on hw2/hw2/NUnitTests.cs
> +            Assert.AreEqual("MyTestIgnoredWithExpectedException", testMethods[7].Name);
Заметили же такое)
Исправил

2017-10-26 12:48 UTC, Decorus2009 commented on hw2/hw2/NUnitTests.cs
> +                .Find(methodInfo => methodInfo.Name == "MyTestSimpleEmpty");
Исправил

2017-10-26 12:48 UTC, Decorus2009 commented on hw2/hw2/Properties/AssemblyInfo.cs
> +using System.Runtime.CompilerServices;
Исправил

2017-10-26 12:59 UTC, Decorus2009 commented on hw2/hw2/TestDiscoverer.cs
> +                Райдер говорит, про "possible multiple enumeration", но
Кажется, в `TestGroup` остался отладочный `ToString()`. В нем было много приведений в списку. Вроде бы хороший тон - использовать "максимально общие" интерфейсы. Т.е., если выбирать из `IEnumerable<T>` и `List<T>`, стоит выбрать первое.

2017-10-26 12:59 UTC, Decorus2009 commented on hw2/hw2/TestDiscoverer.cs
> +                    testGroups.Add(new TestGroup(type, beforeClassMethods, beforeMethods, testMethods, afterMethods,
Исправил

2017-10-26 13:00 UTC, Decorus2009 commented on hw2/hw2/TestGroup.cs
> +        public IEnumerable<MethodInfo> BeforeClassMethods { get; set; }
Исправил

2017-10-26 13:04 UTC, Decorus2009 commented on hw2/hw2/TestResult.cs
> +        /* Я бы вместо null использовал тут Optional<>, но в C# такого нет? */
Нуллы тут служат как аргументы по умолчанию, чтобы не писать несколько перегрузок. `TestResult` в `TestRunner.cs` конструируется по-разному

2017-10-26 13:07 UTC, Decorus2009 commented on hw2/hw2/TestRunner.cs
> +    public class TestRunner
Сделал. А можно ли сделать TestDiscoverer также статичным?

2017-10-26 13:11 UTC, Decorus2009 commented on hw2/hw2/TestResult.cs
> +        public override string ToString()
При печати статистики в `TestRunner.cs` 
```Console.WriteLine($"Test method \'{testMethod}\'\n{testResult}");```

2017-10-26 13:12 UTC, Decorus2009 commented on hw2/hw2/TestRunner.cs
> +                testGroup.BeforeMethods.ToList().ForEach(memberInfo => Run(type, memberInfo));
Плохая - как я понимаю, потому что создается новый объект списка и в него копируются ссылки на элементы из IEnumerable? Заменил простым "форычем"

2017-10-26 13:17 UTC, Decorus2009 commented on hw2/hw2/MYNUnitTests.cs
> +namespace hw2
Исправил

2017-10-26 13:19 UTC, Decorus2009 commented on hw2/hw2/MYNUnitTests.cs
> +        public void Before2()
Убрал Before2()

2017-10-28 20:42 UTC, VMAtm commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public string Ignore { get; set; }
Просто из вашего кода не было очевидно, как вы используете это поле

2017-10-28 20:49 UTC, VMAtm commented on hw2/hw2/MyAttributes/TestAttribute.cs
> +        public TestAttribute(Type expectedException = null, string ignore = null)
Это называется [object initialization](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer) (именно поэтому и рекомендуют свойства, а не поля).

В обычном коде это выглядело бы так (вызывается конструктор по умолчанию):

    new Test
    {
        Ignore = "some string",
        ExpectedException = typeof(Exception)
    }

В случае атрибутов из-за особенностей синтаксиса скобки становятся круглыми. Просто оставьте свойства и удалите параметры конструктора (и читайте внимательнее объяснения компилятора - это легко гуглится)

2017-10-28 20:49 UTC, VMAtm commented on hw2/hw2/NUnitTests.cs
> +            Почему-то не получилось указать через относительный путь.
Понятно. У VS другое мнение про папку исполнения

2017-10-28 20:51 UTC, VMAtm commented on hw2/hw2/TestDiscoverer.cs
> +                Райдер говорит, про "possible multiple enumeration", но
Согласен. Но если внутри класса вам нужен `IList` - так и используйте его. Просто помните, что `IEnumerable` - это state machine, и не надо его итерировать больше одного раза.

2017-10-28 20:52 UTC, VMAtm commented on hw2/hw2/TestResult.cs
> +        /* Я бы вместо null использовал тут Optional<>, но в C# такого нет? */
Если у вас есть свойства, то вы можете использовать object initializer, см. выше

2017-10-28 20:52 UTC, VMAtm commented on hw2/hw2/TestResult.cs
> +        public override string ToString()
Просмотрел

2017-10-28 20:53 UTC, VMAtm commented on hw2/hw2/TestRunner.cs
> +    public class TestRunner
Вообще говоря, лучше сделать его параметром конструктора того, кто вызывается его методы. Старайтесь избегать `static` классов - в случае одновременного прогона двух разных тестов у вас внезапно вылезет проблема гонки данных

2017-12-03 15:03 UTC, merged