Домашнее задание 3, "Option"
Decorus2009/CSC.NET pull request #6
Opened 2017-10-08 16:03 UTC by Decorus2009

2017-11-01 06:31 UTC, VMAtm requested changes
На данный момент оценка 8/10

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Program.cs
> +﻿namespace hw3
Данный файл нужен только для того, чтобы тип проекта был ConsoleApp. Если вы не используете данный класс, поменяйте тип сборки на библиотеку и удалите  неиспользуемый код.

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +namespace hw3
Пожалуйста, называйте пространства имён с большой буквы. Неделю назад с вами это обсуждали.

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +            if (value == null)
Почему вы запрещаете значению быть `null`?

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +                    throw new ArgumentNullException();
Можно ещё добавить некоторое объяснение для вашего исключения. Выбранный тип немного не соответствует - здесь нет аргумента, который передан вам как `null`

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public static Option<T> None() => new Option<T>();
Подобный метод `None` порождает неоднозначность:

        [Test]
        public void NoneReferenceEqualsNoneTest()
        {
            // падает
            Assert.IsTrue(Option<int>.None() == Option<int>.None());
        }

        [Test]
        public void NoneEqualsNoneTest()
        {
            // проходит успешно
            Assert.AreEqual(Option<int>.None(), Option<int>.None());
        }


Нулевой объект обычно единственен.

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public override int GetHashCode() => IsNone ? 0 : Value.GetHashCode();
Данная реализация `GetHashCode` порождает ещё одну неоднозначность:


        [Test]
        public void NoneGetHashCodeEqualsTest()
        {
            Assert.AreEqual(Option<int>.None().GetHashCode(), Option<string>.None().GetHashCode());
        }

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public static Option<T> Flatten(Option<Option<T>> mapper) => mapper.Value;
Плохая идея не проверять внутреннее значение:


        [Test]
        public void FlattenNoneTest()
        {
            // падает с исключением
            Assert.IsTrue(Option<int>.Flatten(Option<Option<int>>.None()).IsNone);
        }

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public Option<TR> Map<TR>(Func<T, TR> f) => IsNone ? Option<TR>.None() : Option<TR>.Some(f(Value));
`Map` и `Flatten` можно (но необязательно) было сделать extension

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Option.cs
> +            if (obj == null || obj.GetType() != typeof(Option<T>))
Можно просто:

            if (!(obj is Option<T> other))
            {
                return false;
            }

Далее вам доступен объект `other` и он точно не `null` и правильного типа

2017-11-01 06:31 UTC, VMAtm commented on hw3/hw3/Tests.cs
> +    public class Tests
Обычно тесты выносят в отдельный проект - так проще различать и запускать при Continuous Integration сборках

2017-11-01 23:16 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +            if (value == null)
Тут хочется явно дать понять, что Option либо хранит что-то осмысленное, либо он `None`. А что такое `Option.Some(null)`? Можно не кидать исключение, а просто сделать `IsSome = false` В задании про это ничего явно сказано, поэтому решил выбрать подход, аналогичный джавовому

2017-11-01 23:25 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +                    throw new ArgumentNullException();
Решил для полноты добавить `OptionException`

2017-11-01 23:45 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +        public static Option<T> None() => new Option<T>();
Добавил статическое поле уровня класса 
`private static readonly Option<T> _none = new Option<T>();`, теперь первый тест не падает

2017-11-01 23:57 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +        public Option<TR> Map<TR>(Func<T, TR> f) => IsNone ? Option<TR>.None() : Option<TR>.Some(f(Value));
А не могли бы Вы чуть подробнее объяснить? В чем преимущество? Синтаксически вид вызова методов сохранится же

2017-11-02 00:11 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +        public static Option<T> Flatten(Option<Option<T>> mapper) => mapper.Value;
Добавил проверку

2017-11-02 00:44 UTC, Decorus2009 commented on hw3/hw3/Program.cs
> +﻿namespace hw3
Создал подпроект Option как ClassLibrary. Ссылаюсь на него из проекта hw3, в котором оставил только тесты

2017-11-02 01:00 UTC, Decorus2009 commented on hw3/hw3/Tests.cs
> +    public class Tests
Вынес в отдельный проект

2017-11-02 10:51 UTC, Decorus2009 commented on hw3/hw3/Option.cs
> +        public override int GetHashCode() => IsNone ? 0 : Value.GetHashCode();
Как уже писал выше, объект `None` я сделал единственным. Данный тест не падает, т.к. `GetHashCode()` возвращает `0` независимо от того, чем параметризован `Option`. Но тут немного неясно: единственность `None` - это в принципе для Option, т.е., для любых значений `T`? Или единственность - это в отношении только какого-то конкретного `T`? Думаю, что скорее первое

2017-11-08 20:53 UTC, VMAtm approved these changes

2017-11-08 20:53 UTC, VMAtm commented on hw3/Option/Option.cs
> +        private static readonly Option<T> _none = new Option<T>();
Статические поля класса стоит инициализировать в статическом же конструкторе

2017-11-08 20:53 UTC, VMAtm commented on hw3/Test/Properties/AssemblyInfo.cs
> +using System.Runtime.CompilerServices;
Ненужный `using`

2017-11-08 20:53 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public Option<TR> Map<TR>(Func<T, TR> f) => IsNone ? Option<TR>.None() : Option<TR>.Some(f(Value));
Сравните:

    var none = Option<Option<int>>.None();
    // текущий вариант
    Console.WriteLine(Option<int>.Flatten(none).IsNone);
    // extension метод
    Console.WriteLine(none.Flatten().IsNone);

Запись [на мой взгляд] получилась короче и понятней. В глобальном плане ничего не поменяется - это тот же статический метод.

2017-11-08 21:12 UTC, VMAtm commented on hw3/hw3/Option.cs
> +        public override int GetHashCode() => IsNone ? 0 : Value.GetHashCode();
Ну, я бы не сравнивал работу `generic` в Java и C# - в `Java`, насколько я помню, просто затирается информация о типе в момент исполнения (поэтому и работает `<?>`), в `C#` же вы можете оперировать `T` в момент исполнения.

Да, вы правы, в текущей реализации есть привязка к конкретному типу (про это и был комментарий про неоднозначность вашей реализации `GetHashCode`). Единственный для всех `None`было бы сложно сделать - потребовался бы базовый нетипизированный класс, изменение в `Map`, `Flatten` и `Equals`, и само решение было бы не особо красивым.

2017-11-08 21:17 UTC, VMAtm commented on hw3/hw3/Option.cs
> +            if (value == null)
`Option<string>.Some(null)` - это строка со значением `null`. Это как в базах данных, есть `DBNull` и есть заполненная ячейка с пустым значением. То есть третье состояние.

Отмечу, что реализация `Maybe` монады различается у различных авторов: http://mikehadlow.blogspot.com/2011/01/monads-in-c-5-maybe.html
https://mikhail.io/2016/01/monads-explained-in-csharp/

так что вы не одиноки в сомнениях про `Some(null)`.

2017-12-03 15:06 UTC, merged