Домашнее задание 5, "Многопоточность"
Decorus2009/CSC.NET pull request #8
Opened 2017-11-08 16:24 UTC by Decorus2009

2017-11-26 09:06 UTC, VMAtm requested changes
На данный момент оценка 8/10

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/ILockBasedQueue.cs
> +        int Size();
Почему не свойство?

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/ILockBasedQueue.cs
> +        bool IsEmpty();
Почему не свойство?

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/LockBasedBlockingArrayQueue.csproj
> +    <Reference Include="System.Xml" />
Последние два проекта вроде не используются

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            if (!Monitor.TryEnter(_tailLock))
Это неожиданное поведение. Обычно `false` возвращается только тогда, когда очередь полна, но не из-за того, что вы не смогли захватить `lock`

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            {
Снова неожиданное поведение

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +                    _head = 0;
Кроме указателей, стоило очищать и сам массив - особенно в случае reference типов, вы оставляете ссылку на объект, даже если сам он давно вышел из области видимости

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            if (Interlocked.Increment(ref _size) > 0)
Может ли быть ситуация, когда `_size` становится меньше нуля?

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockBasedBlockingArrayQueue/Tests.cs
> +                producers.Add(new Thread(() => queue.Enqueue(value)));
Старайтесь создавать потоки тогда, когда это действительно необходимо. Обычно хватает `TPL`

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            int currentTail;
Зачем они вне цикла?

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            while (true)
Не используйте бесконечных циклов. Дайте коду шанс закончить метод в любом случае

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +                Thread.Yield();
В общем случае рекомендуется использовать не сам метод `Yeild`, а вспомогательный класс `SpinWait`, который в свою очередь уже будет решать, когда на самом деле вызывать `Yield`

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +                Thread.Yield();
Ссылки по теме

https://referencesource.microsoft.com/#System/sys/system/collections/concurrent/BlockingCollection.cs,481

https://referencesource.microsoft.com/#mscorlib/system/threading/SpinWait.cs,39bd72970cc926fe

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            T currentResult;
Снова можно сделать внутри цикла

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +                currentResult = _storage[currentHead];
Должно быть атомарно, это обращение по ссылке в пределах `Int32`

https://stackoverflow.com/a/11745701/213550
https://stackoverflow.com/a/2193445/213550

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            if (!CAS(ref _tail, (currentTail + 1) % _capacity, currentTail))
Снова неожиданное поведение.

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            // если голова не изменилась, то предыдущее присвоение (currentResult = _storage[currentHead]) валидно, все ок
Снова может свалится при непустой очереди

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +        // запускать 3 cas'а - можно получить неконсистентное состояние, когда отработает только часть cas'ов.
Например, можно было завести отдельное поле-флаг для операции очистки, чтобы все остальные ждали в цикле, пока оно отработает. Правда, в этом случае код стал бы на порядок сложнее.  Здесь же стоило бы обнулять ещё и массив.

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/Tests.cs
> +// Можно их как-то объединить, передав просто нужный интерфейс очереди для тестирования?
Вроде было при разборе домашнего задания про тесты: http://nunit.org/docs/2.5/parameterizedTests.html должно помочь. Вы можете сделать массив типа `ILockBasedQueue[]` и для каждого его элемента будут вызываться тесты

2017-11-26 09:06 UTC, VMAtm commented on hw5/Philosophers/Philosopher.cs
> +        private volatile bool _stopFlag; // check for happens before https://habrahabr.ru/post/133981/
Ключевое слово `volatile` в C# сломано (обсуждение по теме: https://stackoverflow.com/a/17530556/213550), аккуратнее с ним. Обычно в многопоточном программировании для отмены операций используют `CancellationToken`. Замечание необязательно к исправлению

2017-11-26 09:06 UTC, VMAtm commented on hw5/Philosophers/Philosopher.cs
> +                    if (_debug) Console.WriteLine("{0} has taken left fork", _id);
Обычно делают через `Debug.WriteLine`: https://msdn.microsoft.com/en-us/library/system.diagnostics.debug.writeline.aspx

2017-11-26 09:06 UTC, VMAtm commented on hw5/Philosophers/Program.cs
> +                philosophers.Add(new Philosopher(i + 1, forks[i], forks[(i + 1) / n], maxThinkTime, maxEatTime, debug));
Если `i` равно `n - 1`, чему равно значение `(i + 1) / n`?

2017-11-26 09:06 UTC, VMAtm commented on hw5/Philosophers_C++/main.cpp
> +        phils.emplace_back(i + 1, &forks[(i + 1) % N], &forks[i], think_delay, eat_delay);
А здесь у вас `%`.

2017-11-26 09:06 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +        // запускать 3 cas'а - можно получить неконсистентное состояние, когда отработает только часть cas'ов.
Другие студенты делали цикл из `TryDequeue` как полумеру

2017-11-26 09:06 UTC, VMAtm commented on hw5/Philosophers/Philosopher.cs
> +    public class Philosopher
Почему вы не добавили для философов тесты? Например, что через некоторое время все поели хотя бы один раз.

2017-11-28 00:50 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/ILockBasedQueue.cs
> +        int Size();
Исправил

2017-11-28 00:51 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/ILockBasedQueue.cs
> +        bool IsEmpty();
Исправил

2017-11-28 00:54 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedBlockingArrayQueue.csproj
> +    <Reference Include="System.Xml" />
Исправил

2017-11-28 21:27 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            if (!Monitor.TryEnter(_tailLock))
Честно говоря, совсем неочевидно, что тут требуется. Является ли данный метод блокирующим или нет. По мне, название говорит о том, что тут делается одна попытка вставить элемент в очередь. И неважно, почему вдруг его вставить не удалось, из-за того, что кто-то сейчас параллельно вставляет (не смогли взять лок) или очередь полна. С Вашего позволения, я в четверг спрошу у преподавателя, как лучше поступить и тогда подправлю

2017-11-28 21:32 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +                    _head = 0;
Исправил, но неужели здесь нельзя полагаться на работу GC? Утечек памяти здесь быть не может, т.к. буфер закольцован.

2017-11-28 23:22 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            if (Interlocked.Increment(ref _size) > 0)
Смотря, что Вы имеете ввиду. Если речь идет о переполнении типа, то вряд ли, т.к. размер ограничен емкостью. В этом коде другой поток перед ```if``` параллельно увеличить размер не сможет,  т.к. схвачен лок. А значит, размер может только уменьшаться, если он больше 0. ```if (Interlocked.Increment(ref _size) > 0)``` со строгим равенством именно потому, что размер может быть 0. ```Interlocked.Increment``` возвращает инкрементированное значение.

2017-11-28 23:38 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/Tests.cs
> +                producers.Add(new Thread(() => queue.Enqueue(value)));
Исправил

2017-11-28 23:49 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            int currentTail;
На самом деле это небольшая перестраховка от которой, скорее всего, никакого толку. В цикле можно крутиться довольно долго, и, получается, что на каждой итерации цикла на стек будут помещаться локальные переменные ```currentTail``` и ```currentHead```, а потом они же будут с него сниматься. Это более затратно, чем вообще не совершать вышеупомянутой лишней работы. Я не знаю, как тут сработает компилятор, скорее всего, он это соптимизит. Учитывая, что это примитивы, он просто положит их на стек один раз при вызове функции, даже если они были бы объявлены в цикле. В общем, тут для меня вопрос, как лучше поступить. Будет хорошо, если растолкуете этот момент.

2017-11-28 23:52 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            int currentTail;
И еще, в цикле я их инициализирую и проверяю, что можно работать дальше. Можно, конечно, цикл распространить на весь метод, но тогда возрастет вложенность кода. Этого не хочется

2017-11-29 01:00 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +                Thread.Yield();
Тут назрел вопрос. Идея lockfree заключается в том, чтобы избежать впадания в ядро, через взятие мьютексов и т.д., поскольку это довольно дорогие операции. Оказывается, что порой менее затратно крутиться в ```while(true)``` в пространстве пользователя. Когда же мы вызываем ```Yield``` напрямую или через ```SpinWait```, неважно, в конечном счете поток заснет, и, возможно, произойдет смена контекста, что ни разу не lockfree. Там в чем же тут смысл ```Yield```?

2017-11-29 23:23 UTC, Decorus2009 commented on hw5/Philosophers/Philosopher.cs
> +                    if (_debug) Console.WriteLine("{0} has taken left fork", _id);
Исправил

2017-11-29 23:24 UTC, Decorus2009 commented on hw5/Philosophers_C++/main.cpp
> +        phils.emplace_back(i + 1, &forks[(i + 1) % N], &forks[i], think_delay, eat_delay);
Понял ошибку, спасибо

2017-11-29 23:25 UTC, Decorus2009 commented on hw5/Philosophers/Philosopher.cs
> +    public class Philosopher
Подумал, что такое проще тестить просто глядя на статистику работы в логе или консоли. Добавил

2017-11-30 17:06 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            while (true)
Мы с преподавателем этот момент обсудили как раз. Мы же пишем lock-free, не wait-free. Поэтому тут ```while(true)``` допустимы. Да и вообще, сколько реализаций таких штук видел, в основном используется такое кручение в потенциально бесконечном цикле. Цитата из википедии: "Для алгоритмов без блокировок гарантируется системный прогресс по крайней мере одного потока. Например, поток, выполняющий операцию «сравнение с обменом» в цикле, теоретически может выполняться бесконечно, но каждая его итерация означает, что какой-то другой поток совершил прогресс, то есть система в целом совершает прогресс."

2017-11-30 17:09 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            if (!Monitor.TryEnter(_tailLock))
Исправил на более каноничное решение

2017-11-30 17:09 UTC, Decorus2009 commented on hw5/LockBasedBlockingArrayQueue/LockBasedQueue.cs
> +            {
Опять же, не был уверен, что этот метод может блокироваться. Исправил

2017-12-01 01:06 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/Tests.cs
> +// Можно их как-то объединить, передав просто нужный интерфейс очереди для тестирования?
Удалось соединить тесты для обеих реализаций очередей. Использовал TestCaseSource, который использовал две предопределенных очереди, которые живут все время тестирования. К сожалению, нельзя в таком случае добавить метод, помеченный ```[SetUp]```, чтобы перед каждым тестом очереди очищать. Поэтому в каждом тестовом методе приходится руками вызывать ```queue.Clear();```.  Через параметризованный ```[TestFixture]``` мне не удалось что-то запустить тесты на Generic Test Fixtures с параметрами.

2017-12-01 01:09 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/Tests.cs
> +// Можно их как-то объединить, передав просто нужный интерфейс очереди для тестирования?
Я слил два проекта с разными реализациями очередей в один, в котором есть общий интерфейс и две реализации, LockBased и LockFree, а также общие тесты. К сожалению, замечания к предыдущему коду теперь, похоже, "outdated", прошу прощения. Тем не менее, я постарался там их подправить, а также некоторые моменты прокомментировал. Все изменения теперь, получается, просто лежат в новом проекте.

2017-12-01 01:11 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            if (!CAS(ref _tail, (currentTail + 1) % _capacity, currentTail))
Исправил

2017-12-01 01:11 UTC, Decorus2009 commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            // если голова не изменилась, то предыдущее присвоение (currentResult = _storage[currentHead]) валидно, все ок
Исправил

2017-12-05 04:47 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +                Thread.Yield();
`Yield` - это всё-таки не использование `lock`. При вызове этого метода возможно, что управление вернётся этому же потоку. Если вызывать `SpinWait`, то есть вероятность повисеть без обращения и сделать операцию успешно. `Lock-free` - это про то, что потоки не блокируются - если один не может выполнить операцию, он уступает место другим, а не ест ресурсы системы зря.

2017-12-05 04:51 UTC, VMAtm commented on hw5/LockFreeBlockingArrayQueue/LockFreeQueue.cs
> +            while (true)
Согласен, и всё же замечание было про то, что бесконечные циклы стоит использовать как можно меньше. В вашем коде действительно сложно добавить проверки в `while` так, чтобы это выглядело красиво - не у всех так получилось. Замечания общие для всех.

2018-01-09 20:53 UTC, merged